### ISSUE TITLE
Improved notifications

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#1131]
- [ ] Migrate all to be backed by react-email
- [ ] Add metadata to batch subscriber/unsubscriber emails
- [ ] Allow plexing between instant/daily/weekly/monthly, depending on the type
