### ISSUE TITLE
Allow subscribers to manage their own tags

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#1168]
This will have to be opt-in, since many newsletters _don't_ want to expose tags to their subscribers, but the flow can be something along the lines of:

1. A setting under **Subscriber management** like, "Let subscribers choose their own tags". If that toggle is selected, show a list of tags so that the author can choose _which_ tags are exposed to subscribers.
3. A dedicated 'manage subscription page' (maybe this needs to be blocked on https://github.com/buttondown-email/roadmap/issues/626?) that is linked to at the footer of emails and is prompted when a subscriber logs in that has the list of enabled tags.

---

As a preliminary jumping off point, I think we can construct magic URLs for authors to add, something like:

```
buttondown.email/<username>/subscribers/<id>/tags/<tagid>
```

That we document and let folks send out as they may.
```[tasklist]
### Tasks
- [ ] Add backend flag for enabling subscription management
- [ ] Add basic `/management/subscribers/foo` page
- [ ] Augment emails to include link to management page
- [ ] Augment archives to include link to management page
- [ ] Surface flag in frontend
```

**Comment by taptapkaboom** [comment]
Yeah I like this!
