### ISSUE TITLE
Make the in-app email previewer suck less

### ISSUE THREAD

**Issue by benborgers** [buttondown/roadmap#1315]
- [ ] Honor newsletter-level CSS
- [ ] Honor the chosen template
- [ ] Live preview for headers/footers (https://github.com/buttondown/roadmap/issues/2257)
- [ ] Tweets are not styled correctly (https://github.com/buttondown/roadmap/issues/1081)
- [ ] Template variables need dummy values (https://github.com/buttondown/roadmap/issues/1177)
