### ISSUE TITLE
Refresh documentation architecture + content strategy

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#1716]
### Content

- [ ] Getting started
  - [ ] Registration and setup
  - [ ] Importing
  - [ ] Building your base
  - [ ] Getting a custom domain
  - [ ] Hosting
  - [ ] Sending 
  - [ ] Sending your first email
  - [ ] Scheduling an email
  - [ ] Markdown
  - [ ] Share images
  - [x] Billing
- [ ] Advanced features
  - [ ] CSS
  - [x] Tags
  - [x] Metadata
  - [x] RSS-to-email
  - [ ] Surveys
  - [ ] Paid subs
  - [x] Multiple newsletters
  - [ ] Automations
  - [ ] Teams
  - [x] Dedicated IP
  - [ ] Comments
- [ ] Tutorials
  - [ ] Automations sequences
  - [ ] Collecting names
  - [ ] Customizing list views
  - [ ] Drafting emails via the API
  - [ ] Scheduling emails via the API
- [ ] Dreamhost
- [ ] Migration guides
  - [ ] AWeber
  - [ ] Benchmark
  - [ ] Campaign Monitor
  - [ ] CC
  - [ ] ConvertKit
  - [ ] EmailOctopus
  - [ ] FeedBlitz
  - [ ] Mailchimp
  - [ ] Mailcoach
  - [ ] Mailerlite
  - [ ] Moosend
  - [ ] Revue
  - [ ] Substack
  - [x] Tinyletter
- [ ] API
  - [ ] Emails
  - [ ] Subscribers
  - [ ] Changelog
  - [ ] Tags
  - [ ] Images
  - [ ] Newsletters
  - [ ] Exports
  - [ ] Bulk actions
  - [ ] Automations
  - [x] Comments
- [ ] Integrations
  - [x] Blogger
  - [x] Carrd
  - [x] Discord
  - [ ] Duda
  - [ ] Fathom
  - [ ] Framer
  - [ ] Linktree
  - [ ] Plausible
  - [ ] Stripe
  - [x] Wordpress
- [ ] Esoterica
- [ ] Kudos
- [ ] Affiliate
- [ ] Subscriber referrals
- [ ] Glossary
- [ ] Template variables
- [x] Automations reference
- [ ] Privacy 
- [ ] Data exports
- [x] Offboarding
- [ ] Law enforcement
- [x] Screen reader

### Tasks

- [x] Really implement search
- [ ] Add description metadata to pages
- [x] Add sticky footer with copyright and social links
- [ ] Add analytics
- [x] Lightbox
- [x] Video support (e.g. `/share-images`)
- [x] iFrame / loom support (e.g.  `/blogger`)
- [x] Add anchor support to enum lists, so we can e.g. link to `/event-types#subscriber.created`
- [ ] Add tracking information for searches
- [x] Add code-highlighting to Markdoc
- [ ] Allow collapsing overlong code samples
- [x] Add basic table component
- [x] Add link to buttondown.email application
- [x] Update TypeScript code example to use `fetch` (and name it "JavaScript")
- [x] Automatically run `npm run search-index`
- [ ] Sentry instrumentation for measuring search times
- [ ] Loading state for search
- [x] Dedupe "Introduction" in search
- [ ] Add anchors to h1/h2/etc tags
- [ ] Show a mini table of contents on the right
- [x] Mobile-optimize

### Inspo

- https://skiff.com/ui/facepile
- https://duffel.com/docs
- https://developers.attio.com/docs/using-webhooks
- https://resend.com/docs/knowledge-base/introduction

**Comment by jmduke** [comment]
- [ ] Better empty state / no results state in search — it should prompt folks to email us or file a ticket if they can't find what they're looking for

**Comment by smonette** [comment]
We need a few replacement snippets for old-docs components:

- [ ] `<MultiLanguageSnippet>` Primarily in Tutorials.
- [ ] `<Playground>` Primarily in Tutorials
- [ ] `<Notice>` Across many article types

**Comment by smonette** [comment]
- [ ] The "/using-markdown" page needs a way to display output examples.

Old docs [screenshot](https://share.cleanshot.com/7PtLn1Fr)

**Comment by jmduke** [comment]
- [ ] Add a link to [Discussions](https://github.com/buttondown/discussions/discussions), per https://github.com/buttondown/discussions/discussions/29
