### ISSUE TITLE
Refresh old screenshots

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#1942]
Some  screenshots are clearly old. We should fix that!

Examples:

- [x] https://docs.buttondown.email/migration-guides/convertkit
- [x] https://docs.buttondown.email/getting-started/importing-your-data
- [x] https://docs.buttondown.email/migration-guides/aweber
```[tasklist]
### Tasks
```

**Comment by madelinezday** [comment]
Just sent the first round of edits (for the ConvertKit guide) in a new PR!

**Comment by madelinezday** [comment]
Just sent a PR for the AWeber migration guide!

**Comment by madelinezday** [comment]
Submitted PR for "Importing Your Data" guide on 1/23!

**Comment by jmduke** [comment]
Closing this as it's obviated by https://github.com/buttondown/roadmap/issues/1716.
