### ISSUE TITLE
Add Zapier OAuth support

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#2055]
### Tasks

- [X] 

  [GitHub: Let’s build from here](https://github.com/buttondown/monorepo/pull/2020)
- [ ] setup in zapier
- [ ] get PR merged
- [ ] 
- [ ] *  somehow test migration flow from the old API key version into new OAuth version in Zapier
  *  test flow for new integration on OAuth
  *  figure out if we need to deprecate it now or if we can do that later on
  *  figure out if we should send an email to affected users on the steps forward. In that case, we should probably provide step-by-step instructions in the docs.
  *

**Comment by jmduke** [comment]
simple task, should only take like ten minutes tops I'm sure

**Comment by catdevnull** [comment]
target for now is log into Zapier, no need to allow other developers to create their own keys for now, etc.
