### ISSUE TITLE
Replies 2.0

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#2162]
First implementation of tracked replies did a fine job but has lots of rough edges. Let's fix 'em, and create a nice interface in the app to view Replies (a la Comments).
```[tasklist]
### Tasks
- [ ] Parse and maintain attachments
- [x] On the backend, create `Conversation` and `Reply` objects for performance's sake
- [ ] Use `username@replies.buttondown.com` instead of `replies+uuid@buttondown.email`
- [ ] Do a better job with formatting
- [ ] Provide more context in the body of the Reply notification (See Steph's comment below)
```

**Comment by smonette** [comment]
A customer email with a great example around formatting: [Helpscout #5660](https://secure.helpscout.net/conversation/2715669050/5660?viewId=7228473)

Specifically:
- [ ] Providing context of what a reader is replying to (Newsletter name etc)
- [ ] Preserving line breaks in the reply so that signature lines don't run together
