### ISSUE TITLE
Surveys 1.1

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#2498]
A catch-all for a number of obvious + useful improvements to surveys to integrate them more seamlessly within existing workflows.

```[tasklist]
### Tasks
- [ ] https://github.com/buttondown/roadmap/issues/2692
- [x] Add the ability to add internal notes to surveys (https://github.com/buttondown/roadmap/issues/1860)
- [ ] https://github.com/buttondown/roadmap/issues/2645
- [ ] https://github.com/buttondown/roadmap/issues/2726
- [ ] https://github.com/buttondown/roadmap/issues/2648
```
