### ISSUE TITLE
Omnibus: things that need documentation

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#2522]
- [ ] Using `!important` for most CSS rules
- [x] New UI for choosing columns
- [ ] Pre-flight checks
- [ ] New DMARC information
- [ ] How tracked replies work
- [ ] Customizing meta tags
- [ ] Recovering an old draft of an email using history
- [ ] How to integrate with `cargo.site`
- [x] Updating issue numbers
- [x] FAQ: "help! I accidentally deleted all my subscribers!"
- [x] Breakdown of various email event types
- [x] Quickstart guide for retrieving analytics data
- [ ] What's a payment link?
- [ ]  How do I have email before custom subscribe form inputs?
- [x] What's the difference between permanent + temporary failure?
- [ ] Do imported subscribers have to confirm their interest?
- [ ] Sending emails to tags (https://github.com/buttondown/roadmap/issues/1166)
- [x] `forloop.counter` (https://secure.helpscout.net/conversation/2551843877/3768?folderId=7228478)
- [ ] How do I change my statement description in Stripe?
- [x] Precedence: Bulk
- [x] Uploading images
```[tasklist]
### Tasks
- [x] The /v1/surveys endpoint
- [x] API 'expansion' (see /v1/comments)
- [ ] Types of temporary failures ("Timed out", ...)
- [x] How do I format array parameters with the API (`?status=1&status=2`)
- [x] What is Irrelevant status for RSS items
- [ ] Template variables in subject lines
- [ ] Why don’t we need mailing address for CAN-SPAM anymore?
- [ ] How to turn off image optimization
- [ ] How email replies work
- [ ] Tag grouping (category:Tag syntax)
- [ ] Slack webhooks
- [ ] How to make daily/weekly RSS options via tags
- [x] How to remove header from Modern template
- [ ] How to show some content only in email/web (via `medium` template variable)
- [x] How does subscriber cleanup work?
- [ ] "Previewing drafts" (punting until summer)
- [ ] "Creating your first automation"
- [ ] Branding (custom colors, icons, etc)
- [x] Localization: what is it, and how does it work today?
- [ ] How to show or hide borders on tables
- [x] Why is my email stuck in "About to Send"?
```

**Comment by smonette** [comment]
Break apart `/css` and `/customizing-your-web-presence` into separate articles for different concerns (and mediums)

My suggestion:

- [ ] - Feature → CSS on Web
- [ ] - Feature → CSS in Email
- [ ] - FAQ → Can I use a custom font? (Sort of, yes! <links to the other two>)

**Comment by smonette** [comment]
- [ ] Reference → Composing Emails has no articles or content
- [ ] Review API docs and fill in more enum desrciptions (for example `/subscriber-source` descriptions)

**Comment by smonette** [comment]
- [ ]  "Previewing drafts" (punting until summer)
- [ ] "Creating your first automation"
