### ISSUE TITLE
Improvements to `/settings/billing/pricing`

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#2596]
- [x] Add upgrade button a la Typefully
- [ ] Break out stuff into sections
- [ ] Add affordance for plan needed for current number of ubs
- [ ] Add cute icons
```[tasklist]
### Tasks
- [ ] Improve mobile experience
```

**Comment by jmduke** [comment]
(Fillout has a really good bit of prior art here!)
