### ISSUE TITLE
Rebuild sending flow

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#263]
1. Sending to two tags simultaneously
2. Sending to arbitrary subscribers
3. Sending based on metadata

## Additional work

- [ ] Whatever primitive we end up with on the email end we should _also_ apply to Automations and RSS-to-Email so that folks can flexibly filter/send within those, too.

**Comment by jeremycherfas** [comment]
It will be great to see this, as I can then imagine being able to target emails more effectively.

**Comment by adityag81** [comment]
> 1. Sending to two tags simultaneously
> 2. Sending to arbitrary subscribers
> 3. Sending based on metadata

Looking forward to this granular option of targeting specific subscribers, which can be really helpful. 

Cheers!

**Comment by sewingbuttondown** [comment]
4. Sending based on everyone except a particular tag.  :D

**Comment by adityag81** [comment]
> 4. Sending to everyone _except_ a particular tag.  :D

Yes, this!

**Comment by jmduke** [comment]
That one's already possible! Tap on a tag twice in the 'tags' dropdown; it'll exclude that tag.

**Comment by efletch** [comment]
Request to send to two tags simultaneously within automation as well

https://secure.helpscout.net/conversation/2542605886/3641

**Comment by jmduke** [comment]
Rough order of attack here:

- [ ] Migrate 'send draft' button + flow into the `preview` pane. (This also lets us use that exact modal and flow for other previewable emails, like the welcome email.)
- [ ] Move 'send' (finalization/completion modals) from modal into a drawer
- [ ] Move scheduling _into_ the above drawer so that folks only schedule right as they're ready to send their email
- [ ] Combine recipients and tags modal into single "audience" pane that goes into the above drawer

**Comment by jmduke** [comment]
@mary-ext So, audience restructuring. I'll start with the backend first.

Current state of the world (this logic is encapsulated within `fetch_subscribers`), we basically filter on three things:

1. The `audience` (comparing `subscriber.type` against `email.type`)
2. The included and excluded tags
3. The `filters`, which consists of a single possible filter (`subscriber.price`, to allow sending to a specific _tier_)

In order to be able to do things like "send to folks tagged FOO _or_ BAR", let alone complex stuff like "send to folks tagged FOO _or_ (tagged BAR and with a metadata of first_name='Mary'), we should collapse 2 and 3 into a single, composable filtering abstraction. (There's no reason we shouldn't _also_ collapse 1 into this abstraction, and I think indeed we can with no real backend changes, but this seems like an easier way to piecemeal it.)

On the backend side, I think this schema just works. We'll need to migrate the API and a bunch of legacy stuff, but if we have a FilterGroup json blob on an email that gives us the flexibility we want:

![image](https://github.com/user-attachments/assets/343fd0c4-b36c-4aac-83c1-fbf86ddf76dd)

---

This leads us to the frontend. I think this should not actually be that bad, since we already have the `Tag filters` component, and more complex prior art in `FilterInput` over in automations. The main thing we need is the ability to compose & nest the individual filters.

I think Notion's approach is worth ~stealing~ adapting pretty much wholesale:

![image](https://github.com/user-attachments/assets/52e5e6ec-762f-415f-9c75-6cb3cebb7099)

I don't like how many ellipsis menus they throw everywhere, but the general idea of nesting here works well I think. Feel free to set an arbitrary limit on the number of nested filters (maybe 3?) 

---

This is a long way of saying: build a more advanced `Tag filters` component that allows the nesting above, with the assumption that it's `v-model`-ing a `data.filter_groups` attribute in the schema outlined above. I can take the backend work to actually build + surface that, and then we should be good to go.

**Comment by mary-ext** [comment]
Seems good, should we pull this out into a new issue? @jmduke
