### ISSUE TITLE
Unship `RichTextArea` input in favor of `DraftBody`

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#2791]
We have a `RichTextArea` component that can be generously described as a poor man's `DraftBody`. Here's an example usage, in `/settings/subscribing`:

![image](https://github.com/buttondown/roadmap/assets/461046/1a215100-f3cd-430c-a198-3e2c213994f5)

This is used in a number of places:

- `/settings/design`
- `/settings/subscribing`
- Sending custom emails from automations (`ActionSetting`)
- The 'description' field in `/settings/basics`
- The `teaser` field in `/emails/:id/recipients`.

This component is, bluntly, bad. Here are some ways where it is bad:

- You can't choose between Markdown/WYSIWYG mode.
- Many things like image uploading and round-trip conversions are re-implemented
- You can't reference surveys like you can in `DraftBody`

I propose that we unship its usage entirely in favor of the component currently known as `DraftBody`. Put another way — this draft body component is really good, and fully featured. Let's decouple it from the `emails/:id` route so we can plop it into random contexts.

A rough plan of attack here:

```[tasklist]
### Tasks
- [ ] Migrate `DraftBody` to setup style. This doesn't accomplish anything in of itself, but will make further refactors cleaner
- [ ] Refactor `DraftBody` to use a generic document as a model, rather than an `Email`.
- [ ] Refactor `DraftBody` to handle editorMode and survey fetching within itself rather than delegating that to the parent component.
```

Some design notes (I'm sure I'm missing things):

- We should shift the `PreviewPanel` to be part of the `DraftBody` itself (so that using the DraftBody component also lets us get previewing for free.) Consider this blocked on https://github.com/buttondown/monorepo/pull/974, which I will endeavor to have merged by 6/1.

I'm sure I'm missing many nuances — let me know!
