### ISSUE TITLE
Automations 2.0

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#2832]
```[tasklist]
### Tasks
- [ ] Allow sorting by name
- [ ] Shift from toggle to dropdown
- [ ] Add 'send test email' to dropdown
- [ ] Add deletion to dropdown
- [ ] Allow pausing/resuming from the detail, too
- [ ] Add support for multiple actions for a given automation
- [ ] Allow filtering external events for a given email by the automation that sent them
- [ ] More granular times (not just morning/evening)
- [ ] History support just like with emails
```
