### ISSUE TITLE
Omnibus: improvements to CI

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#2927]
```[tasklist]
### Tasks
- [ ] Add step for running just app/frontend-lint (so we know when we have unused code/deps)
- [ ] Add step for checking deltas in frontend bundle sizes (https://github.com/relative-ci/bundle-stats?tab=readme-ov-file looks promising)
- [ ] Add step for generating `prisma` schema in the Marketing site
- [ ] Add step for checking for database migration conflicts _before_ running tests
- [ ] Add step for checking that the PR references a roadmap issue
```
