### ISSUE TITLE
Email scheduling grab bag

### ISSUE THREAD

**Issue by benborgers** [buttondown/roadmap#3356]
```[tasklist]
### Tasks
- [ ] There's no way of unscheduling an email from the finalization drawer (although you can from the ••• menu on the emails list)
- [ ] "Email will be going out..." copy should technically be "Once finalized, this email will go out..." to emphasize that finalization step still has to occur
- [x] _The "finalize" button on the right hand side panel is often invisible and inaccessible, at least on iPad. I can briefly see it when I scroll down the page, but then the page snaps back to a view where it is off the bottom. I could only get to it by pressing the tiny green send button in the main window._
```
