### ISSUE TITLE
Subscribers as first-party users

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#626]
## Milestone one: `/settings/subscriptions`

- [ ] Populate `Subscriber.account` upon subscriber creation
- [ ] Unship `Comment.account`  in favor of `Comment.subscriber.account`
- [ ] Add internal `/subscriptions` endpoint
- [ ] Add settings page
