### ISSUE TITLE
Streamlined importing process

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#72]
**Milestone 1**
- [ ] For supported import sources, ask user if they want us to kick off the subscriber import automatically
- [ ] Expand subscriber import to take ZIPs (if valid) and optionally ask user if they want us to kick off the archive import

**Miscellany**
- [ ]  Parse historical events
- [ ]  Prompt for connecting Stripe account

**Comment by jmduke** [comment]
(@catdevnull I will be writing up a lot for this, no need to really poke around it yet.)
