### ISSUE TITLE
Rebuild WYSIWYG editor

### ISSUE THREAD

**Issue by jmduke** [buttondown/roadmap#79]
**In short**: remove the current WYSIWYG editor (ribbon style) with a new interface that uses both tooltipping & commands.

This issue is _related to_ but does not block/overlap two other big goals with the editor:

1. A vastly improved previewer (https://github.com/buttondown/roadmap/issues/1315)
2. A vastly streamlined sending flow (https://github.com/buttondown/roadmap/issues/1944)

```[tasklist]
### Tasks
- [ ] Add support for footnotes
- [ ] Add support for tweets
- [ ] Add support for "pull quotes"
- [ ] Add support for color selection
- [ ] Add support for share buttons
- [x] Allow customizing button text
- [ ] Add support for poetry
- [ ] Add support for LaTeX
- [x] Add support for surveys
- [ ] Add support for syntax highlighting within codeblocks
```

**Comment by toddlburns** [comment]
Thank you for bringing back the dedicated preview pane!

**Comment by jmduke** [comment]
Just pushed a change to re-enable the preview pane; it should be rolling out in the next hour or so.

**Comment by jmduke** [comment]
Changes for the following should be landing this afternoon:

```
Icons look a little squished when viewing the preview pane
D&D is very janky on Safari
Embeds are not working as expected in rich text mode
```

**Comment by james-baker** [comment]
New editor notes so far:

- No way to do long dashes ("--" or "---") in rich text?
- Switching between markdown and rich text changes the preview render (of how dashes are interpreted), so... will the final render be based on the mode I'm in at the moment I send the email?
- Without a toolbar in markdown mode, I find myself switching over to rich text just for making a link
- Replacing the preview content with "Rendering..." causes a large layout-jump-flash on the page
- Preview is quite narrow in width and can't be resized (or expanded, popped out, etc)

Let me conclude by also saying, I do think recent work (which I realize is still in progress) is definitely heading in the right direction, and I appreciate any improvements to this very core piece of our experience.

**Comment by rghedin** [comment]
Some quirks/weird behaviors I noticed recently:

* in Rich Text mode, the toolbar could be fixed (always visible) to be on-hand when writing a long message. (I was writing a long message and had to scroll up and down to insert images.)
* When I alternate between Rich Text and Markdown modes, Rich Text messes up with lists in Markdown (it creates double breaklines and adds weird spacing in blank lines between list itens). This also removed all custom HTML. (I use some `<span class="">` to highlight words and they all vanished when I changed from Markdown to Rich Text and back to Markdown.)

All of this using Firefox 92.0 on macOS.

I second what @james-baker said: the new editor is awesome!

**Comment by james-baker** [comment]
Testing using "send draft to yourself", I find that what lands in my inbox DOES vary based on the text mode that's active when I click the send button. "--" versus "–"

**Comment by jmduke** [comment]
🙏 Appreciate it, you two! Added the stuff you mentioned to the big list up top.

**Comment by jmduke** [comment]
@rghedin do you mind sharing an example piece of content for the list issue you outlined?

**Comment by rghedin** [comment]
Sure! I just noticed that it only messes up if I make an edit while in Rich text mode. (Although it changed the list signal, from `*` to `-`, without any modification.)

I recorded a short video to demonstrate:

https://user-images.githubusercontent.com/19216581/133856769-1ba029e0-adc7-498d-9c4c-ad9728f45b17.mp4

**Comment by jmduke** [comment]
The `command` abstraction is kind of nice, though I think a ways' off:

https://tiptap.dev/experiments/commands

**Comment by jmduke** [comment]
(Cleaned up the list of todos a bit; this is gonna be a long-term one.)

**Comment by benborgers** [comment]
Nits:

- [ ] When I hit `/` and down-arrow, the viewport should scroll down with the selection (`Element.scrollIntoView()`?)
- [ ] When I hit `/` and then insert a table, the "/" character remains. 
- [ ] The +C, etc options for tables are kinda indiscoverable (hover menu on the right and bottom edges? That's where I went to look for them)
- [ ] If a line contains `/` anywhere in the line, the slash menu activates, and takes over the keyboard commands
  - <img src=https://github.com/buttondown/roadmap/assets/30215449/85ac4d4e-91e5-42e1-b444-e1f67fd0861e height=300 />
  - In this situation above, hitting the Enter key doesn't do anything (presumably because it's _supposed to_ take action within the slash menu, not the larger editor). This makes it feel like you can't do a newline after a link (unless you add an extra space after the link to escape the slash menu).

**Comment by jmduke** [comment]
- [ ] When you add a link in the popup, you should be able to click away from it without having to hit the checkmark

**Comment by krangor** [comment]
Just jumping in here to signal support for footnotes! (They SORT of work if you use Markdown. But quickly un-work if you switch to another editor view. It's fragile.)

**Comment by jmduke** [comment]
Agreed!
